// error handling
/* try, catch throw */

/* console.log("step 1");

function gethSam(a,b){
    return a * b
}


function completed(){
    console.log("weather forcast");

}
try{
    gethSam();
}catch(error){
console.log(error);
}finally{
    completed();
}
 */
//exception
/* const username = "50";
const age  = 20; */
// if(typeof username !== "string"){
// throw Error("why dont use other");
// }

/* if(age<30){
    throw Error("your age is greter than value");
    throw TypeError("your age is greter than value");
} */

function hero(){
    return a * b;
}
hero(10, 20);
try{
    
}catch(error){
console.log("cant valid");
}

console.log("hello sir");